<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$moduleName = $this->getRequest()->getModuleName();
$controllerName = $this->getRequest()->getControllerName();
$actionName = $this->getRequest()->getActionName();
$route = $moduleName.'/'.$controllerName.'/'.$actionName;
?>
<?php if ($this->isEnabled()) : ?>
    <?php $this->addAttribute('pageType', $route); ?>
    <?php $childScript = $this->getChildScript(); ?>
    <script>
    <?php if (!empty($childScript)) : ?>
            <?php if($this->hasAttributes()) : ?>
            dataLayer = [<?= $this->getAttributesAsJson(); ?>];
            <?php endif; ?>
            <?= $childScript; ?>
    <?php endif; ?>
    </script>
<?php endif; ?>
